#
# This is free software, lisence use MIT.
# 
# Copyright (C) 2019 P3TERX <https://p3terx.com>
# Copyright (C) 2019 KFERMercer <KFER.Mercer@gmail.com>
# 
# <https://github.com/KFERMercer/OpenWrt-CI>
# 

name: OpenWrt-CI20200203

#on:
#  schedule:    
#    - cron: 0 20 1 1 1
  
#  push:
#    branches: 
#      - master     
#  watch:
#    types: [started]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          ref: master

     
     
      - name: create bin directory
        run: |
          mkdir bin
          cp README ./bin/my.comfig
         
    
      - name: Upload artifact
        env:
          EXPORT: DATE=$(date+"%Y%m%d")
        uses: actions/upload-artifact@master
        with:
          name: $DATE
          path: ./bin/
          
          
          
          
